title: My Area
description: >
  My Area<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svyh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
locale: "ko-KR"

author:
  name: 'svyh'
  avatar: '/images/logo.png'
  github_username:  svyh  
  email: '' 
  logo: '/images/logo.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


